export const colleges = [
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Applied Electronics",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Electronic and Communication Engineering",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "IT",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Automobile Engineering",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "M-DIT",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "M-DIT",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "M-DIT",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "M-DIT",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "M-DIT",
    subject: "electronics And Computer Engineering",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "M-DIT",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "M-DIT",
    subject: "Electrical And Computer Engineering",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "M-DIT",
    subject: "Cyber security",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Computer Science And Design",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Chemical Engineering",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Biomedical Engineering",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Information Technology",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Cyber security",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Artifical Intelligence & Data Science",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Biotechnology",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Engineering Physics",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Chemical Engineering",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Materials Science And Engineering",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Production Engineering",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Biotechnology",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering(AI & ML)",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "",
    subject: "",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "AL-FURQAN ARABIC COLLEGE,NADAPURAM",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc GENETICS",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "BAITHUL IZZA ARABIC COLLEGE,NARIKKUNI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 4.8,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "CALICUT UNIVERSITY CENTRE FOR COSTUME & FASHION DESIGNING",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "CENTRE FOR COMPUTER SCIENCE & INFORMATION TECHNOLOGY",
    subject: "B.Sc INFORMATION TECHNOLOGY",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "DARUL MA-RIFA ARABIC COLLEGE,ODUNGAKAD,PUTHUPADY",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.8,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "BA PUBLIC ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "B.Com FINANCE",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "ARABIC & HISTORY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA HINDI LANGUAGE & LITRATURE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA ECONOMETRICS & DATA MANAGEMENT",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA ARABIC LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "JALALIYA WOMEN'S ARABIC COLLEGE,KUTTIKKATUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc BIOTECHNOLOGY",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA MULTIMEDIA",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.COM COOPERATION",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.8,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA ECONOMICS ",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.SC POLYMER CHEMISTRY",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 5.8,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.5,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.9,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 7.6,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA HRM",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 4.5,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 4.8,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 4.3,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "SALAFIYYA ARABIC COLLEGE COLLEGE,MEPPAYUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "SAQAFATHUL ISLAM ARABIC COLLEGE,PARAKKADAVU",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.SC FAMILY & COMMUNITY SCIENCE",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.3,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.9,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.0,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.8,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 4.2,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.2,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.6,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 7.5,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 7.2,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 7.9,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 5.0,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.2,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.4,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.7,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 6.3,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 7.8,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 6.8,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 4.1,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 7.4,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 5.7,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 6.0,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 7.1,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 4.4,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 7.7,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 4.6,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 4.7,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 6.9,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 5.3,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA MALAYALAM LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA HINDI LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 5.1,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 6.1,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 6.5,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 5.4,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 8.0,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 6.6,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 6.0,
  },
];
