// const colleges = [
//     { name: "KMCTCE", location: "Calicut", subject: "Computer Science", gpa: 7.5 },
//     { name: "KMCTCE", location: "Calicut", subject: "Civil Engineering", gpa: 7.5 },
//     { name: "KMCTCE", location: "Calicut", subject: "Mechanical Engineering", gpa: 7.5 },

//     { name: "MDIT", location: "Vadakara", subject: "Computer Science", gpa: 7.5 },
//     { name: "MDIT", location: "Vadakara", subject: "Civil Engineering", gpa: 7.5 },
//     { name: "MDIT", location: "Vadakara", subject: "Mechanical Engineering", gpa: 7.5 },

//     { name: "NAM", location: "Peringathoor", subject: "BCOM CA", gpa: 5.5 },
// ];

const colleges = [
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Applied Electronics",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Electronic and Communication Engineering",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "IT",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Automobile Engineering",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "M-DIT",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "M-DIT",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "M-DIT",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "M-DIT",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M-DIT",
    subject: "electronics And Computer Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M-DIT",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M-DIT",
    subject: "Electrical And Computer Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "M-DIT",
    subject: "Cyber security",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Computer Science And Design",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Chemical Engineering",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    subject: "Biomedical Engineering",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Information Technology",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Cyber security",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    subject: "Artifical Intelligence & Data Science",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Biotechnology",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Engineering Physics",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Chemical Engineering",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Materials Science And Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    subject: "Production Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Biotechnology",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Computer Science And Engineering(AI & ML)",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    subject: "Civil Engineering",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "",
    subject: "",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "AL-FURQAN ARABIC COLLEGE,NADAPURAM",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc GENETICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "BAITHUL IZZA ARABIC COLLEGE,NARIKKUNI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "BA COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "CALICUT UNIVERSITY CENTRE FOR COSTUME & FASHION DESIGNING",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "CENTRE FOR COMPUTER SCIENCE & INFORMATION TECHNOLOGY",
    subject: "B.Sc INFORMATION TECHNOLOGY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "DARUL MA-RIFA ARABIC COLLEGE,ODUNGAKAD,PUTHUPADY",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "BA PUBLIC ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "B.Com FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    subject: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "ARABIC & HISTORY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "BA HINDI LANGUAGE & LITRATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    subject: "BA ECONOMETRICS & DATA MANAGEMENT",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BA ARABIC LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "JALALIYA WOMEN'S ARABIC COLLEGE,KUTTIKKATUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc BIOTECHNOLOGY",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "BA MULTIMEDIA",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.COM COOPERATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA ECONOMICS ",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.SC POLYMER CHEMISTRY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    subject: "BA HRM",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "SALAFIYYA ARABIC COLLEGE COLLEGE,MEPPAYUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "SAQAFATHUL ISLAM ARABIC COLLEGE,PARAKKADAVU",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.SC FAMILY & COMMUNITY SCIENCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    subject: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    subject: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    subject: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    subject: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA HISTORY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA MALAYALAM LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BA HINDI LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    subject: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
];

const courseDifficulty = {
  "Computer Science": 7.0,
  "Civil Engineering": 7.0,
  "Mechanical Engineering": 7.0,
  "BCOM CA": 5.0,
};

function recommendColleges() {
  const gpa = parseFloat(document.getElementById("gpa").value);
  const location = document.getElementById("location").value.toLowerCase();
  const subjects = document
    .getElementById("subject")
    .value.toLowerCase()
    .split(",")
    .map((s) => s.trim());

  const recommendations = colleges.filter((college) => {
    const courseDifficultyLevel = courseDifficulty[college.subject];
    if (courseDifficultyLevel && gpa < courseDifficultyLevel) {
      return false; // Skip this course if GPA is lower than the difficulty level
    }
    return (
      college.location.toLowerCase().includes(location) &&
      subjects.some((subj) => college.subject.toLowerCase().includes(subj))
    );
  });

  displayRecommendations(recommendations);
}
function displayRecommendations(recommendations) {
  const suggestions = recommendations.map((college) => college.subject);
  const popUpContent = `
        <h2>Recommendations</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Subject</th>
                <th>GPA</th>
            </tr>
            ${recommendations
              .map(
                (college) => `
                <tr>
                    <td>${college.name}</td>
                    <td>${college.location}</td>
                    <td>${college.subject}</td>
                    <td>${college.gpa}</td>
                </tr>
            `
              )
              .join("")}
        </table>
        <h2>Suggestions</h2>
        <p>${suggestions.join(", ")}</p>
    `;

  const popUpWindow = window.open(
    "",
    "Recommendations",
    "width=600,height=400"
  );
  popUpWindow.document.body.innerHTML = popUpContent;
}
const recommendations = colleges.filter((college) => college.gpa >= 7.0);
displayRecommendations(recommendations);
