// import colleges from "./colleges";

const colleges = [
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Applied Electronics",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Electronic and Communication Engineering",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "IT",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Automobile Engineering",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "M-DIT",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "M-DIT",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "M-DIT",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "M-DIT",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M-DIT",
    dept: "electronics And Computer Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M-DIT",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M-DIT",
    dept: "Electrical And Computer Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "M-DIT",
    dept: "Cyber security",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Computer Science And Design",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Chemical Engineering",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Biomedical Engineering",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Information Technology",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Cyber security",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Artifical Intelligence & Data Science",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Biotechnology",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Engineering Physics",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Chemical Engineering",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Materials Science And Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Production Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Biotechnology",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering(AI & ML)",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "",
    dept: "",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "AL-FURQAN ARABIC COLLEGE,NADAPURAM",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc GENETICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "BAITHUL IZZA ARABIC COLLEGE,NARIKKUNI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "CALICUT UNIVERSITY CENTRE FOR COSTUME & FASHION DESIGNING",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "CENTRE FOR COMPUTER SCIENCE & INFORMATION TECHNOLOGY",
    dept: "B.Sc INFORMATION TECHNOLOGY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "DARUL MA-RIFA ARABIC COLLEGE,ODUNGAKAD,PUTHUPADY",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "BA PUBLIC ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "B.Com FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "ARABIC & HISTORY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA HINDI LANGUAGE & LITRATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA ECONOMETRICS & DATA MANAGEMENT",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA ARABIC LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "JALALIYA WOMEN'S ARABIC COLLEGE,KUTTIKKATUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc BIOTECHNOLOGY",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA MULTIMEDIA",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.COM COOPERATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA ECONOMICS ",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.SC POLYMER CHEMISTRY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 58,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 55,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 49,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 76,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA HRM",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 45,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 43,
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "SALAFIYYA ARABIC COLLEGE COLLEGE,MEPPAYUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "SAQAFATHUL ISLAM ARABIC COLLEGE,PARAKKADAVU",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.SC FAMILY & COMMUNITY SCIENCE",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 73,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 59,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 70,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 48,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: 42,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 52,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 56,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 75,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: 72,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 79,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: 50,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 62,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 64,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 67,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 63,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 78,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: 68,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 41,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 74,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: 57,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: 60,
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 71,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 44,
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 77,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 46,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 47,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 69,
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: 53,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA MALAYALAM LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA HINDI LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: 51,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: 61,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: 65,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: 54,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: 80,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: 66,
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: 60,
  },
];

let collegesData; // Global variable to store the parsed CSV data
// c=
// Function to load the CSV file and parse it
function loadCSV() {
  fetch("clgdata.csv")
    .then((response) => response.text())
    .then((data) => {
      collegesData = data.split("\n").map((row) =>
        row.split(",").reduce((obj, val, index) => {
          const header = [
            "collegename",
            "department",
            "location",
            "percentage",
          ];
          obj[header[index]] = isNaN(val) ? val.trim() : parseFloat(val);
          return obj;
        }, {})
      );
    });
}

function recommendColleges() {
  const percentage = parseFloat(document.getElementById("gpa"));
  const location = document.getElementById("location").value.toLowerCase();
  //   const departments = document
  //     .getElementById("department")
  //     .value.toLowerCase()
  //     .split(",")
  //     .map((s) => s.trim());

  let temp = colleges[0];
  console.log(
    "per:",
    temp.gpa,
    " > ",
    percentage,
    " => ",
    temp.gpa > percentage,
    "loc",
    temp.location
  );

  const recommendations = colleges.filter((college) => {
    return (
      college.gpa > percentage &&
      college.location.toLowerCase().includes(location)
      //    &&
      //   departments.some((dep) => college.department.toLowerCase().includes(dep))
    );
  });

  displayRecommendations(recommendations);
}

function displayRecommendations(recommendations) {
  const table = document.getElementById("recommendations-table");
  const tbody = document.getElementById("recommendations");
  tbody.innerHTML = "";

  if (recommendations.length === 0) {
    const row = tbody.insertRow();
    const cell = row.insertCell();
    cell.colSpan = 4;
    cell.textContent = "No colleges found matching your criteria.";
  } else {
    recommendations.forEach((college) => {
      const row = tbody.insertRow();
      row.insertCell().textContent = college.collegename;
      row.insertCell().textContent = college.department;
      row.insertCell().textContent = college.location;
      row.insertCell().textContent = college.percentage;
    });
  }
}
